#!/bin/sh
#inkVerbSerf! verb.ink
set -e

# This downloads and updates the Inker core files of a Verber™, including knights and inklists
## If the verbdomain mod is in effect, it will automatically run again at the end of this update
## This also runs scripts that make other changes that may affect the Verber

# How to use:
## ./updateinker


# Download and unpack the latest checked version from the Inkver repo
cd /var/local/ink/
/var/local/verb/serfs/inkget ink-update
unzip ink-update.zip
rm -f ink-update.zip

# Run the update script
/var/local/ink/ink-update/update

# Remove the entire updater
rm -rf /var/local/ink/ink-update

